// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: auth/otp_status.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OtpStatus int32

const (
	OtpStatus_OTP_STATUS_UNSPECIFIED OtpStatus = 0
	OtpStatus_QUEUED                 OtpStatus = 1
)

// Enum value maps for OtpStatus.
var (
	OtpStatus_name = map[int32]string{
		0: "OTP_STATUS_UNSPECIFIED",
		1: "QUEUED",
	}
	OtpStatus_value = map[string]int32{
		"OTP_STATUS_UNSPECIFIED": 0,
		"QUEUED":                 1,
	}
)

func (x OtpStatus) Enum() *OtpStatus {
	p := new(OtpStatus)
	*p = x
	return p
}

func (x OtpStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OtpStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_otp_status_proto_enumTypes[0].Descriptor()
}

func (OtpStatus) Type() protoreflect.EnumType {
	return &file_auth_otp_status_proto_enumTypes[0]
}

func (x OtpStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OtpStatus.Descriptor instead.
func (OtpStatus) EnumDescriptor() ([]byte, []int) {
	return file_auth_otp_status_proto_rawDescGZIP(), []int{0}
}

var File_auth_otp_status_proto protoreflect.FileDescriptor

const file_auth_otp_status_proto_rawDesc = "" +
	"\n" +
	"\x15auth/otp_status.proto\x12\x04auth*9\n" +
	"\tOtpStatus\x12\x1a\n" +
	"\x16OTP_STATUS_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x01\"\x04\b\x02\x10\n" +
	"B$Z\"github.com/tgkzz/ecom/innerpb/authb\x06proto3"

var (
	file_auth_otp_status_proto_rawDescOnce sync.Once
	file_auth_otp_status_proto_rawDescData []byte
)

func file_auth_otp_status_proto_rawDescGZIP() []byte {
	file_auth_otp_status_proto_rawDescOnce.Do(func() {
		file_auth_otp_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_otp_status_proto_rawDesc), len(file_auth_otp_status_proto_rawDesc)))
	})
	return file_auth_otp_status_proto_rawDescData
}

var file_auth_otp_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_otp_status_proto_goTypes = []any{
	(OtpStatus)(0), // 0: auth.OtpStatus
}
var file_auth_otp_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_otp_status_proto_init() }
func file_auth_otp_status_proto_init() {
	if File_auth_otp_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_otp_status_proto_rawDesc), len(file_auth_otp_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_otp_status_proto_goTypes,
		DependencyIndexes: file_auth_otp_status_proto_depIdxs,
		EnumInfos:         file_auth_otp_status_proto_enumTypes,
	}.Build()
	File_auth_otp_status_proto = out.File
	file_auth_otp_status_proto_goTypes = nil
	file_auth_otp_status_proto_depIdxs = nil
}
